# arrowParens
# bracketSpacing
# endOfLine
# htmlWhitespaceSensitivity
# insertPragma
# jsxBracketSameLine
# jsxSingleQuote
# printWidth
# proseWrap
# quoteProps
# requirePragma
# semi
# singleQuote
# tabWidth
# trailingComma
# useTabs
# vueIndentScriptAndStyle
printWidth: 80
semi: false
singleQuote: true
tabWidth: 2
trailingComma: 'es5'
