name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes clister kubeconfig save gittix-do
      - run: kubectl rollout restart deployment manifests-depl
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
